### ISSUE TITLE
Converting the C example sources to python3

### ISSUE THREAD

**Issue by hy-kiera** [nnstreamer/nnstreamer-example#158]
This is an project of team-3 in OSS Contributhon.  

[The current examples](https://github.com/nnstreamer/nnstreamer-example/tree/master/native) based C language are too difficult to follow them by beginner.  
Therefore, we decided to convert all of them to examples based Python 3.

**TODO**
- [ ] Converting the examples to python3
- [ ] Release to [PYPI](https://pypi.org/)
- [ ] Write python tutorials
